### PR TITLE
ffmpeg: enable vaapi

### PR DESCRIPTION
**Pull request by Andarwinux**
ref: https://github.com/mpv-player/mpv/pull/12847

### CODE REVIEW

**Comment by shinchiro** [comment]
What's example of ffmpeg command line to use vaapi?

**Comment by Andarwinux** [comment]
> What's example of ffmpeg command line to use vaapi?

```
ffmpeg -init_hw_device vaapi:0 -hwaccel vaapi -hwaccel_output_format vaapi -i VIDEO -vf scale_vaapi=w=1920:h=1080 -c:v hevc_vaapi out.mkv
```

**Comment by shinchiro** [comment]
Does `vaon12_drv_video.dll` need to exist along mpv.exe built with vaapi?

**Comment by Andarwinux** [comment]
> Does `vaon12_drv_video.dll` need to exist along mpv.exe built with vaapi?

Yes, this is the vaapi driver, you can still run mpv without this driver, but if you want to use vaapi hwdec, you have to install this driver.

**Comment by Andarwinux** [comment]
mpv has merged vaapi-win32

**Comment by zhongfly** [comment]
I would suggest that the `vaon12_drv_video.dll` file does not need to be included in the release, and that people can download it elsewhere, for example: https://github.com/pal1000/mesa-dist-win, even https://www.nuget.org/packages/Microsoft.Direct3D.VideoAccelerationCompatibilityPack/ has this [dll](https://nuget.info/packages/Microsoft.Direct3D.VideoAccelerationCompatibilityPack/1.0.2)
Since we will rarely build it, it is likely to be in an unmaintained state, and there is no need to maintain `mesa` package in this repo.

**Comment by Andarwinux** [comment]
> I would suggest that the `vaon12_drv_video.dll` file does not need to be included in the release, and that people can download it elsewhere, for example: https://github.com/pal1000/mesa-dist-win, even https://www.nuget.org/packages/Microsoft.Direct3D.VideoAccelerationCompatibilityPack/ has this [dll](https://nuget.info/packages/Microsoft.Direct3D.VideoAccelerationCompatibilityPack/1.0.2) Since we will rarely build it, it is likely to be in an unmaintained state, and there is no need to maintain `mesa` package in this repo.

I don't intend to build it in CI, so I added it to the [removed](https://github.com/shinchiro/mpv-winbuild-cmake/blob/6d342c342ba33742a7df04e5fe9309b704859d1f/packages/CMakeLists.txt#L120) list. users can just build it locally if they need to. As for those prebuilt versions, I don't recommend them, they are too old and built with GCC/MSVC.

**Comment by Andarwinux** [comment]
Maybe in the future we can add a new workflow for build such packages that are not part of the mpv build dependencies but are runtime related, e.g. VVL, Mesa, etc.

**Comment by zhongfly** [comment]
But you forget to add the `mesa.cmake` in this pr

**Comment by zhongfly** [comment]
> Maybe in the future we can add a new workflow for build such packages that are not part of the mpv build dependencies but are runtime related, e.g. VVL, Mesa, etc.

Maybe this workflow should be in https://github.com/shinchiro/mpv-packaging
Also missing dll files for angle: `libEGL.dll` `libGLESv2.dll`.

**Comment by Andarwinux** [comment]
> But you forget to add the `mesa.cmake` in this pr

I accidentally lost mesa.cmake during rebase, thanks for the heads up.

> Maybe this workflow should be in https://github.com/shinchiro/mpv-packaging

Share the toolchain cache maybe cumbersome in different repositories.


> Also missing dll files for angle: `libEGL.dll` `libGLESv2.dll`.

It's already possible to extract the latest Clang LTO+CFI ANGLE from Chrome/Electron, so there's no point in building ANGLE on your own.

**Comment by Andarwinux** [comment]
I didn't realize this would be merged so soon. If anyone wants to compile mesa, they may need to modify `-Dvideo-codecs` for the time being, since https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/26320 hasn't been merged yet.

**Pull request merged**
