### PR TITLE
libzimg: switch to bitbucket

### PR DESCRIPTION
**Pull request by zhongfly**
seems to have switched hosters

### CODE REVIEW

**Comment by Andarwinux** [comment]
~~This new repository is not even accessible through a browser.~~

**Comment by zhongfly** [comment]
> This new repository is not even accessible through a browser.

?
https://bitbucket.org/the-sekrit-twc/zimg/src/master/

image

BtbN/FFmpeg-Builds have switched to it: https://github.com/BtbN/FFmpeg-Builds/commit/ae3f10661bbc07a99b6693cfc665280945e1fc60

**Comment by Andarwinux** [comment]
> ?

It looks like their auto-redirect is broken.

**Comment by shinchiro** [comment]
Thank goodness bitbucket finally support `--filter` command

**Pull request merged**
