### PR TITLE
lld: force set O3,lto-O3,lto-CGO3

### PR DESCRIPTION
**Pull request by Andarwinux**
This will ensure O3 is always used during linking

### CODE REVIEW

**Comment by shinchiro** [comment]
I dont have time to test this. Just pray this will not introduce bugs in future

**Comment by zhongfly** [comment]
Do I need to run the `ninja llvm-clang` command after `.in` file update like this pr?

**Comment by Andarwinux** [comment]
you don't need to rebuild anything, we currently only enable lto for mpv, this change only works when linking mpv.

**Comment by shinchiro** [comment]
Trigger cmake configure with `ninja rebuild_cache` or rerun with cmake command should regenerate the file

**Pull request merged**
