### PR TITLE
ffmpeg: re-enable libgme

### PR DESCRIPTION
**Pull request by Andarwinux**
It's not a shit anymore.

### CODE REVIEW

**Comment by zhongfly** [comment]
No one has reported an inability to play these formats, so maybe no one needs it at all?
It disabled at 2019 ( see https://github.com/shinchiro/mpv-winbuild-cmake/commit/882c456109777bd388986b743e1c27b7cb6392fd )
Suggest putting it in the list： https://github.com/shinchiro/mpv-winbuild-cmake/blob/02cd11b247331d89c500f994c0759b3583f4668c/packages/CMakeLists.txt#L121

|Format|System|
|--- |--- |
|AY|ZX Spectrum/Amstrad CPC|
|GBS|Nintendo Game Boy|
|GYM|Sega Genesis/Mega Drive|
|HES|NEC TurboGrafx-16/PC Engine|
|KSS|MSX Home Computer/other Z80 systems (no FM sound)|
|NSF/NSFE|Nintendo NES/Famicom (with VRC 6, Namco 106, and FME-7 sound)|
|SAP|Atari systems using POKEY sound chip|
|SPC|Super Nintendo/Super Famicom|
|VGM/VGZ|Sega Master System/Mark III, Sega Genesis/Mega Drive,BBC Micro|

**Comment by Andarwinux** [comment]
Most people do not use mpv to play these formats. Some libmpv-based players choose to build mpv on their own. it would be convenient to include libgme in our builds, eliminating the need to use outdated proprietary closed-source players.

**Comment by zhongfly** [comment]
Have you tested it with gcc? https://github.com/libgme/game-music-emu/issues/83

**Comment by Andarwinux** [comment]
> Have you tested it with gcc? [libgme/game-music-emu#83](https://github.com/libgme/game-music-emu/issues/83)

Yeah, no problem.

**Comment by shinchiro** [comment]
No

**Pull request closed without merging**
