### PR TITLE
toolchain misc

### PR DESCRIPTION
**Pull request by Andarwinux**

### CODE REVIEW

**Comment by zhongfly** [comment]
`mimalloc` `zlib-host` `zstd-host` are best placed in the llvm folder, as they are only needed by llvm.

**Comment by CharlesMengCA** [comment]
typo
`elseif(package MATCHES "mingw-a64") `
should be
`elseif(package MATCHES "mingw-w64") `

**Comment by CharlesMengCA** [comment]
```
fatal: destination path 'llvm' already exists and is not an empty directory.
fatal: destination path 'llvm' already exists and is not an empty directory.
fatal: destination path 'llvm' already exists and is not an empty directory.
CMake Error at /home/cm/mpv-winbuild-cmake/build64/toolchain/mimalloc-prefix/tmp/mimalloc-gitclone.cmake:39 (message):
  Failed to clone repository: 'https://github.com/microsoft/mimalloc.git'


```

**Comment by CharlesMengCA** [comment]
```
[188/3373] Building CXX object lib/Option/CMakeFiles/LLVMOption.dir/Option.cpp.o
[189/3373] Building Attributes.inc...
FAILED: include/llvm/IR/Attributes.inc /home/cm/mpv-winbuild-cmake/build64/toolchain/llvm-prefix/src/llvm-build/include/llvm/IR/Attributes.inc 
cd /home/cm/mpv-winbuild-cmake/build64/toolchain/llvm-prefix/src/llvm-build && /home/cm/mpv-winbuild-cmake/build64/toolchain/llvm-prefix/src/llvm-build/bin/llvm-min-tblgen -gen-attrs -I /home/cm/mpv-winbuild-cmake/src_packages/llvm/llvm/include/llvm/IR -I/home/cm/mpv-winbuild-cmake/build64/toolchain/llvm-prefix/src/llvm-build/include -I/home/cm/mpv-winbuild-cmake/src_packages/llvm/llvm/include /home/cm/mpv-winbuild-cmake/src_packages/llvm/llvm/include/llvm/IR/Attributes.td --write-if-changed -o include/llvm/IR/Attributes.inc -d include/llvm/IR/Attributes.inc.d
/home/cm/mpv-winbuild-cmake/build64/toolchain/llvm-prefix/src/llvm-build/bin/llvm-min-tblgen: error while loading shared libraries: cannot apply additional memory protection after relocation: Cannot allocate memory
[190/3373] Building GenVT.inc...
FAILED: include/llvm/CodeGen/GenVT.inc /home/cm/mpv-winbuild-cmake/build64/toolchain/llvm-prefix/src/llvm-build/include/llvm/CodeGen/GenVT.inc 
cd /home/cm/mpv-winbuild-cmake/build64/toolchain/llvm-prefix/src/llvm-build && /home/cm/mpv-winbuild-cmake/build64/toolchain/llvm-prefix/src/llvm-build/bin/llvm-min-tblgen -gen-vt -I /home/cm/mpv-winbuild-cmake/src_packages/llvm/llvm/include/llvm/CodeGen -I/home/cm/mpv-winbuild-cmake/build64/toolchain/llvm-prefix/src/llvm-build/include -I/home/cm/mpv-winbuild-cmake/src_packages/llvm/llvm/include /home/cm/mpv-winbuild-cmake/src_packages/llvm/llvm/include/llvm/CodeGen/ValueTypes.td --write-if-changed -o include/llvm/CodeGen/GenVT.inc -d include/llvm/CodeGen/GenVT.inc.d
/home/cm/mpv-winbuild-cmake/build64/toolchain/llvm-prefix/src/llvm-build/bin/llvm-min-tblgen: error while loading shared libraries: cannot apply additional memory protection after relocation: Cannot allocate memory

```

**Comment by shinchiro** [comment]
Whats these commits want to achieve anyway? Why you keep deleting your own comment?

I'll keep disable -mguard=cf -fcf-protection=full except for v3

**Comment by CharlesMengCA** [comment]
Random download failure for zstd and mimalloc. 

Log just said tried download more than 3 times or something like that.

**Pull request closed without merging**
