### PR TITLE
ci: enable lld icf

### PR DESCRIPTION
**Pull request by Andarwinux**
-1MB

### CODE REVIEW

**Comment by zhongfly** [comment]
Why not use `--icf=safe` to avoid issues

**Comment by Andarwinux** [comment]
> Why not use `--icf=safe` to avoid issues

Because `--icf=safe` doesn't reduce size significantly. Chromium has also been using `--icf=all` on all platforms for a couple of years now, and I've done some local testing with no problems.

**Comment by Andarwinux** [comment]
But I'll keep this as a draft for now so that more people can test it.

**Comment by zhongfly** [comment]
> Because `--icf=safe` doesn't reduce size significantly. Chromium has also been using `--icf=all` on all platforms for a couple of years now, and I've done some local testing with no problems.

A 1MB size reduction can hardly be called significant.But this reduction is also welcome if there are no side effects.
Also, the developers of Chromium knew it would be built under `--icf=all` and had the ability to fix the problems it caused.

**Comment by Andarwinux** [comment]
> A 1MB size reduction can hardly be called significant.

True, but `--icf=safe` doesn't even reduce size by 500k.

> the developers of Chromium knew it would be built under `--icf=all` and had the ability to fix the problems it caused.

So I'm hoping to benefit from Chromium's CI and and billions of installed base, and if `--icf=all` has a problem, they'll fix it quickly.

**Comment by zhongfly** [comment]
> So I'm hoping to benefit from Chromium's CI and and billions of installed base, and if `--icf=all` has a problem, they'll fix it quickly.

I'm not saying that `--icf=all` has problem, but that some source codes may have problems with `--icf=all`.
If chromium encounters such an issue, its developers can solve the problem by updating the codes of chromium.

I don't know the specifics, but I've seen articles mentioning that:
>We must note that ICF might cause some issues if you use functions as keys in a map for example. Then the same piece of code - which would normally be two different pieces of code - would practically be used as a map key twice which is obviously a problem.To avoid such issues, you can use `--icf=safe`.

**Comment by Andarwinux** [comment]
Change to `--icf=safe`

**Comment by Andarwinux** [comment]
safe icf seems to be pointless on x86_64 and i686, not sure what's going on with v3 as libssh is blocking the build.

**Comment by Andarwinux** [comment]
May also need to build packages with `-fvisibility=hidden` to enhance the effect, not sure if this breaks build, will try it after work.

**Comment by shinchiro** [comment]
I merged this without much thinking but apparently `-faddrsig` only works for ELF target. For COFF (windows) it doesnt give any effect

https://clang.llvm.org/docs/UsersManual.html#cmdoption-faddrsig

**Comment by Andarwinux** [comment]
> I merged this without much thinking but apparently `-faddrsig` only works for ELF target. For COFF (windows) it doesnt give any effect
> 
> https://clang.llvm.org/docs/UsersManual.html#cmdoption-faddrsig

https://github.com/llvm/llvm-project/commit/6b30240288fc6c0871ea92fcf77c944b0bdd43ad

I suspect it's because they forgot to update the docs.

**Comment by Andarwinux** [comment]
https://github.com/llvm/llvm-project/pull/70037
will send a PR later to revert this change until migration to llvm18.

**Pull request merged**
