### PR TITLE
libsrt: reset to working commit

### PR DESCRIPTION
**Pull request by zhongfly**

### CODE REVIEW

**Comment by CharlesMengCA** [comment]
mpv has a pull request have fixed the ffmpeg issue.

**Comment by zhongfly** [comment]
> ffmpeg need to be reset on 97beb63a660ae9ad6be72da4ee2a3856594118a3 until mpv fixes the problem.
> 
> Didn't try commits after this one. maybe work, maybe not.
> 
> [mpv-player/mpv#13662](https://github.com/mpv-player/mpv/issues/13662)

This pr is just to fix the ffmpeg configuration error that says libsrt not found.

**Comment by Andarwinux** [comment]
The reset operation is only intended to address buildability and runnability issues, for other issues, fixes should be sought as far upstream as possible.

**Comment by Andarwinux** [comment]
https://github.com/Haivision/srt/pull/2906

**Pull request closed without merging**
