### PR TITLE
llvm: update to 18.1

### PR DESCRIPTION
**Pull request by Andarwinux**
LLVM 18.1 is now available.

### CODE REVIEW

**Comment by CharlesMengCA** [comment]
Working fine for my limited testing. :)

**Comment by Andarwinux** [comment]
Currently rust nightly LLVM is bumped to 18.1, so this need be merged in order to continue the gnullvm changes, otherwise the cross-language LTO will be wrong. This is the only thing that blocks AArch64 support, other stuff has been fixed upstream recently without any patch.

**Comment by Andarwinux** [comment]
Added previously missed changes. LLD18.1 can strip DWARF part of pdb when passing -s, generating a minimal binary and pdb with no debugging impact. This also results in a smaller $TARGET_ARCH-w64-mingw32/bin dir. So for LLVM toolchain, manual strip is no longer needed. also avoids strip COFF chksum, in line with GCC and MSVC.

**Comment by shinchiro** [comment]
Please split changes into commits and describe each as concise as possible in commit message. This will made me easy to look up and review

**Comment by shinchiro** [comment]
Looks ok from my view

**Pull request merged**
