### PR TITLE
ci: enable size optimization

### PR DESCRIPTION
**Pull request by Andarwinux**
This reduces the size by about 3 MiB. This brings the v3 build size back to its original size.

### CODE REVIEW

**Comment by shinchiro** [comment]
I dont test it but if there's no performance drop or increase compiling time, you can it to global flag in llvm-compiler.in

**Comment by CharlesMengCA** [comment]
mingw-w64-crt might have problem with the new flags.

error: all .cv_loc directives for a function must be in the same section
error: all .cv_loc directives for a function must be in the same section

**Comment by shinchiro** [comment]
Looks like it is safe to use for building package but not for building toolchain

**Comment by Andarwinux** [comment]
Yes, crt can't be compiled with these flags. In the future it may be necessary to implement per-package FLAGS (PACKAGE_FLAGS?), but for now this is the most convenient way to do it without any changes to the infrastructure.

**Pull request merged**
