### PR TITLE
vapoursynth: update to R66

### PR DESCRIPTION
**Pull request by zhongfly**
Building the 64-bit version with clang was successful.
However, someone in the vapoursynth repository reported R66 not working ([link](https://github.com/vapoursynth/vapoursynth/issues/1033)). Please test if vapoursynth works in this version : https://github.com/zhongfly/mpv-winbuild/actions/runs/8213619280

[wiki](https://github.com/shinchiro/mpv-winbuild-cmake/wiki/Setup-vapoursynth-for-mpv) need update:
https://github.com/vapoursynth/vapoursynth/commit/50d7e27d13a69d91fe885d44d8653e12bc54c711
   * Download and decompress [Python 3.12.x](http://www.python.org/) or Python 3.8.x -- 64 bit embeddable version
   * Decompress the [portable VapourSynth archive](https://github.com/vapoursynth/vapoursynth/releases) into the Python dir and overwrite all existing files.
   * Install pip using [get-pip.py](https://bootstrap.pypa.io/get-pip.py) or any other method.
   * Install the wheel from the *wheel* directory for the chosen Python version.
   * If using Python 3.8 rename *vsscriptpython38.dll* to *vsscript.dll* and delete the original file.

### CODE REVIEW

**Comment by zhongfly** [comment]
R66 portable VapourSynth have updated.
https://github.com/vapoursynth/vapoursynth/issues/1035#issuecomment-1994161177

**Comment by shinchiro** [comment]
Didnt test it but hoped the hash is correct

**Comment by zhongfly** [comment]
> The new R66 Portable seems missed `VapourSynth.dll`, which causes gendef to fail.

https://github.com/vapoursynth/vapoursynth/commit/50b1328fa66de0e275d4b3aa4af738b1f8b45f3a#diff-245fa285b4f915286e4fa4a5412a236ca39d6640311c4ce6a10a7176c89d4398L25

**Comment by shinchiro** [comment]
Reset for now till I got "time" to finally look

**Pull request merged**
